#include "ASCGenInc.h"
/**
*	@Ascension Engine
 *	@file Ascension 2D\Engine\Common\ASCInputNames.h
 *	@brief 
 *	
 *	Copyright()
 *		Copyright © 2011 Matt Dalzell. All Rights Reserved.
 *	
 *********************************************************************************************/
#ifndef _ASCINPUTNAMES_H__Included_1620351545
#define _ASCINPUTNAMES_H__Included_1620351545

#include "ASCInputStructs.h"

namespace ASC
{
	static ASCString m_strDesc[sk_uKeyCount] =
	{	
		"Key_Escape",
		"Key_1",
		"Key_2",
		"Key_3",
		"Key_4",
		"Key_5",
		"Key_6",
		"Key_7",
		"Key_8",
		"Key_9",
		"Key_0",
		"Key_Minus",
		"Key_Equals",
		"Key_Backspace",
		"Key_Tab",
		"Key_Q",
		"Key_W",
		"Key_E",
		"Key_R",
		"Key_T",
		"Key_Y",
		"Key_U",
		"Key_I",
		"Key_O",
		"Key_P",
		"Key_L_Bracket",
		"Key_R_Bracket",
		"Key_Enter",
		"Key_L_Control",
		"Key_A",
		"Key_S",
		"Key_D",
		"Key_F",
		"Key_G",
		"Key_H",
		"Key_J",
		"Key_K",
		"Key_L",
		"Key_Semi_Colon",
		"Key_Apostrophe",
		"Key_Tilde",
		"Key_L_Shift",
		"Key_Backslash",
		"Key_Z",
		"Key_X",
		"Key_C",
		"Key_V",
		"Key_B",
		"Key_N",
		"Key_M",
		"Key_Comma",
		"Key_Period",
		"Key_Slash",
		"Key_R_Shift",
		"Key_Multiply",
		"Key_L_Menu",
		"Key_Space",
		"Key_Caps",
		"Key_F1",
		"Key_F2",
		"Key_F3",
		"Key_F4",
		"Key_F5",
		"Key_F6",
		"Key_F7",
		"Key_F8",
		"Key_F9",
		"Key_F10",
		"Key_Num_Lock",
		"Key_Scroll",
		"Key_NP_7",
		"Key_NP_8",
		"Key_NP_9",
		"Key_Subtract",
		"Key_NP_4",
		"Key_NP_5",
		"Key_NP_6",
		"Key_Add",
		"Key_NP_1",
		"Key_NP_2",
		"Key_NP_3",
		"Key_NP_0",
		"Key_Decimal",
		"Key_OEM_102",
		"Key_F11",
		"Key_F12",
		"Key_F13",
		"Key_F14",
		"Key_F15",
		"Key_Kana",
		"Key_Abnt_C1",
		"Key_Convert",
		"Key_NoConvert",
		"Key_Yen",
		"Key_Abnt_C2",
		"Key_NP_Equals",
		"Key_Prev_Track",
		"Key_At",
		"Key_Colon",
		"Key_Underline",
		"Key_Kanji",
		"Key_Stop",
		"Key_Ax",
		"Key_Unlabeled",
		"Key_Next_Track",
		"Key_NP_Enter",
		"Key_R_Control",
		"Key_Mute",
		"Key_Calculator",
		"Key_Play_Pause",
		"Key_Media_Stop",
		"Key_Volume_Down",
		"Key_Volume_Up",
		"Key_Web_Home",
		"Key_NP_Comma",
		"Key_Divide",
		"Key_Print_Screen",
		"Key_Right_Menu",
		"Key_Pause",
		"Key_Home",
		"Key_Up",
		"Key_Page_Up",
		"Key_Left",
		"Key_Right",
		"Key_End",
		"Key_Down",
		"Key_Page_Down",
		"Key_Insert",
		"Key_Delete",
		"Key_L_Win",
		"Key_R_Win",
		"Key_Apps",
		"Key_Power",
		"Key_Sleep",
		"Key_Wake",
		"Key_Web_Search",
		"Key_Web_Favorites",
		"Key_Web_Refresh",
		"Key_Web_Stop",
		"Key_Web_Forward",
		"Key_Web_Back",
		"Key_My_Computer",
		"Key_Mail",
		"Key_Media_Select"
	};

	static ASCString m_strDescMouse[m_kiInputCount] =
	{
		"MouseX",
		"MouseY",
		"MouseXY",
		"MouseWheel",
		"MouseLButton",
		"MouseRButton",
		"MouseWheelButton",
		"Mouse4Button",
		"Mouse5Button",
		"Mouse6Button",
		"Mouse7Button",
		"Mouse8Button",
	};
    
    static ASCString m_strDescTouch[m_kuTouchInputs] = 
    {
        "Touch_1",
        "Touch_2",
        "Touch_3",
        "Touch_4",
        "Touch_5",
    };
}

#endif //_ASCINPUTNAMES_H__Included_1620351545

